### ISSUE TITLE
Previous version of extension not deleted when trying to update

### ISSUE THREAD

**Issue by Rdornier** [qupath/extension-manager#21]
Hello @Rylern 

I'm trying to update extensions from the extension manager but it seems that previous versions are not removed automatically. Here are the steps I've done

1. Open the Extension Manager
2. Click on **update available** for the extension to update

<img width="1180" height="286" alt="Image" src="https://github.com/user-attachments/assets/3de4375f-00cb-4a67-be89-29bb7ba4989e" />

3. Select the latest version and click on **Update**

<img width="496" height="337" alt="Image" src="https://github.com/user-attachments/assets/e27e7d8e-f665-4ecf-a142-45d9aef9c7d3" />

4. QuPath shows the new version of the extension in the extension manager, which as been successfully installed. However, the previous version hasn't been removed

<img width="812" height="296" alt="Image" src="https://github.com/user-attachments/assets/db276e2c-d4da-4ac8-9163-5f373a2364d8" />

<img width="141" height="96" alt="Image" src="https://github.com/user-attachments/assets/89b70f2b-bdb4-45a2-bcfd-69acba5c7159" />

5. Restart QuPath
6. Open again the extension manager
7. The same extension that we've just updated has been rolled-back to its previous version (0.10.2) and need to be updated again

<img width="800" height="225" alt="Image" src="https://github.com/user-attachments/assets/eef5aa00-f780-435c-ad3c-ea8bda5179e2" />

In order to fix it, I had to close QuPath, manually delete the folder containing the previous version and open QuPath again but the automatic replacement doesn't seem to work.

Thanks and all the best,

Rémy.

**Comment by Rylern** [comment]
Thanks, I managed to reproduce the issue and it should have been fixed in #22. It will appear in the next version of QuPath.

**Comment by Rdornier** [comment]
Hi @Rylern 

I've tested QuPath-0.7.0 but previous versions still cannot be deleted.

```
10:16:45.332	[pool-4-thread-1]	INFO	qupath.ext.extensionmanager.core.ExtensionCatalogManager	QuPath OMERO extension of QuPath catalog installed
10:17:49.32	[JavaFX Application Thread]	DEBUG	qupath.ext.extensionmanager.core.tools.FileTools	The specified path C:\QuPath_Common_Data_0.7\extensions\catalogs\QuPath catalog\QuPath OMERO extension is a non-empty directory
10:17:51.407	[pool-5-thread-1]	DEBUG	qupath.ext.extensionmanager.core.tools.FileTools	Attempting to move C:\QuPath_Common_Data_0.7\extensions\catalogs\QuPath catalog\QuPath OMERO extension to trash
10:17:51.537	[pool-5-thread-1]	DEBUG	qupath.ext.extensionmanager.core.tools.FileTools	Failed to move C:\QuPath_Common_Data_0.7\extensions\catalogs\QuPath catalog\QuPath OMERO extension to trash. Deleting it
10:17:51.537	[pool-5-thread-1]	DEBUG	qupath.ext.extensionmanager.core.tools.FileTools	Deleting children of C:\QuPath_Common_Data_0.7\extensions\catalogs\QuPath catalog\QuPath OMERO extension
10:17:51.537	[pool-5-thread-1]	DEBUG	qupath.ext.extensionmanager.core.tools.FileTools	Deleting children of C:\QuPath_Common_Data_0.7\extensions\catalogs\QuPath catalog\QuPath OMERO extension\v0.2.2
10:17:51.537	[pool-5-thread-1]	DEBUG	qupath.ext.extensionmanager.core.tools.FileTools	Deleting children of C:\QuPath_Common_Data_0.7\extensions\catalogs\QuPath catalog\QuPath OMERO extension\v0.2.2\javadocs-dependencies
10:17:51.537	[pool-5-thread-1]	DEBUG	qupath.ext.extensionmanager.core.tools.FileTools	Deleting children of C:\QuPath_Common_Data_0.7\extensions\catalogs\QuPath catalog\QuPath OMERO extension\v0.2.2\javadocs-dependencies\qupath-extension-omero-0.2.2-javadoc.jar
10:17:51.537	[pool-5-thread-1]	DEBUG	qupath.ext.extensionmanager.core.tools.FileTools	Deleting C:\QuPath_Common_Data_0.7\extensions\catalogs\QuPath catalog\QuPath OMERO extension\v0.2.2\javadocs-dependencies\qupath-extension-omero-0.2.2-javadoc.jar
10:17:51.538	[pool-5-thread-1]	DEBUG	qupath.ext.extensionmanager.core.ExtensionCatalogManager	Error while removing files of QuPath OMERO extension. They won't be deleted	java.nio.file.FileSystemException: C:\QuPath_Common_Data_0.7\extensions\catalogs\QuPath catalog\QuPath OMERO extension\v0.2.2\javadocs-dependencies\qupath-extension-omero-0.2.2-javadoc.jar: The process cannot access the file because it is being used by another process
	at java.base/sun.nio.fs.WindowsException.translateToIOException(Unknown Source)
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
	at java.base/sun.nio.fs.WindowsFileSystemProvider.implDelete(Unknown Source)
	at java.base/sun.nio.fs.AbstractFileSystemProvider.deleteIfExists(Unknown Source)
	at java.base/java.nio.file.Files.deleteIfExists(Unknown Source)
	at qupath.ext.extensionmanager.core.tools.FileTools.deleteDirectoryRecursively(FileTools.java:176)
	at qupath.ext.extensionmanager.core.tools.FileTools.deleteDirectoryRecursively(FileTools.java:171)
	at qupath.ext.extensionmanager.core.tools.FileTools.deleteDirectoryRecursively(FileTools.java:171)
	at qupath.ext.extensionmanager.core.tools.FileTools.deleteDirectoryRecursively(FileTools.java:171)
	at qupath.ext.extensionmanager.core.tools.FileTools.moveDirectoryToTrashOrDeleteRecursively(FileTools.java:77)
	at qupath.ext.extensionmanager.core.ExtensionFolderManager.deleteExtension(ExtensionFolderManager.java:292)
	at qupath.ext.extensionmanager.core.ExtensionCatalogManager.removeExtension(ExtensionCatalogManager.java:475)
	at qupath.ext.extensionmanager.core.ExtensionCatalogManager.installOrUpdateExtension(ExtensionCatalogManager.java:340)
	at qupath.ext.extensionmanager.gui.catalog.ExtensionModificationWindow.lambda$onSubmitClicked$10(ExtensionModificationWindow.java:261)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

10:17:51.540	[pool-5-thread-1]	INFO	qupath.ext.extensionmanager.core.ExtensionCatalogManager	QuPath OMERO extension of QuPath catalog removed

``` 

However, with the new catalog layout, it doesn't tell me that I need to update.

**Comment by Rylern** [comment]
It is not possible to delete a loaded jar on Windows (`The process cannot access the file because it is being used by another process`). Therefore, since QuPath 0.7, a new way of handling extensions was added, which overcomes this limitation. See https://github.com/qupath/extension-manager/pull/28 for more details.

**Comment by Rdornier** [comment]
Ok, so that's expected. Thanks!
